### ISSUE TITLE
How to define composite types available on MongoDB?

### ISSUE THREAD

**Issue by heitoragm** [cwqt/refract#11]
As described here: https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-composite-types
It is possible to define composite types with mongodb, like this: 

```
model Product {
  id     String  @id @default(auto()) @map("_id") @db.ObjectId
  name   String
  photos Photo[]
}

type Photo {
  height Int
  width  Int
  url    String
}
```

Still, it's not clear to me how to achieve that with refract library. Any thoughts?

**Comment by cwqt** [comment]
I wasn't aware this existed until now, personally have no interest in adding support for this as I don't use MongoDB, but PRs are welcome
