### ISSUE TITLE
Wrong type for native mysql type 'Char'

### ISSUE THREAD

**Issue by Fairbrook** [cwqt/refract#16]
In the definition of functions for mysql native types, the Char type appears like so
```
Char: (value: string) =>
```
Shouldn´t  it be a number?

**Comment by cwqt** [comment]
Released on `1.3.6` (made a mistake with 1.3.5 🙃) https://github.com/cwqt/refract/commit/05d79e116a7f9998103a1fc8d7d9b1ae5b046348
