### ISSUE TITLE
How to specify implicit many-to-many relations?

### ISSUE THREAD

**Issue by NexZhu** [cwqt/refract#7]
How to produce Prisma schema like:
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/many-to-many-relations#implicit-many-to-many-relations
```
model Post {
  id         Int        @id @default(autoincrement())
  categories Category[]
}

model Category {
  id    Int    @id @default(autoincrement())
  posts Post[]
}
```

**Comment by cwqt** [comment]
I'll work on adding a `ManyToMany` field type, in the mean-time you can use `Raw()`

```ts
Post
  .Field("id", Int(Id, Default("autoincrement()")))
  .Raw("categories Category[]")
```

**Comment by cwqt** [comment]
Actually you can do:

```ts
const Post = Model('Post');
const Category = Model('Category');

Post
  .Field('id',            Int(Id, Default('autoincrement()')))
  .Relation('categories', OneToMany(Category));

Category
  .Field('id',            Int(Id, Default('autoincrement()')))
  .Relation('posts',      OneToMany(Post));


```

<img width="708" alt="image" src="https://user-images.githubusercontent.com/61694629/173183468-996c21a7-765e-4437-8f74-5809268af633.png">

**Comment by NexZhu** [comment]
> Actually you can do:
> 
> ```ts
> const Post = Model('Post');
> const Category = Model('Category');
> 
> Post
>   .Field('id',            Int(Id, Default('autoincrement()')))
>   .Relation('categories', OneToMany(Category));
> 
> Category
>   .Field('id',            Int(Id, Default('autoincrement()')))
>   .Relation('posts',      OneToMany(Post));
> ```
> 
> <img alt="image" width="708" src="https://user-images.githubusercontent.com/61694629/173183468-996c21a7-765e-4437-8f74-5809268af633.png">

Yeah, I closed because I found this solution, thanks :D

**Comment by NexZhu** [comment]
Better add it to the doc/example  though

**Comment by cwqt** [comment]
https://github.com/cwqt/refract/commit/eb43ae89e879b31daf32de9b0ef0c8f45809290e
