### ISSUE TITLE
[feature request] Add custom comments to generated prisma schema?

### ISSUE THREAD

**Issue by NexZhu** [cwqt/refract#8]
Hi, thanks for this great tool!

I'm thinking maybe something like this:
```ts
User.Comment('This is the user class')
  .Field('id', Int(Id, Default('autoincrement()')), Comment('This is the user ID')
```

Can generate something like:
```prisma
/// This is the user class'
model User {
        /// This is the user ID
	id                        Int                 @id @default(autoincrement())
}
```

So that various generators can use this information.

**Comment by iquabius** [comment]
I think this would be useful for [prisma-nestjs-graphql](https://github.com/unlight/prisma-nestjs-graphql).

The comments are used to instrument the code generator to annotate classes with Nexus' decorators.

**Comment by cwqt** [comment]
Have added this in https://www.npmjs.com/package/@cwqt/refract/v/1.2.0

```typescript
const model = Model("User", "This is the User class");

model
  .Field('id', Int(Id, Default('autoincrement()'), Comment('This is the user ID'));
```

& equally for enums:

```typescript
const Role = Enum("Role", "This is the Role enum", Key("ADMIN"));
```

**Comment by NexZhu** [comment]
@cwqt Thanks, seems like types are not fully updated yet, e.g.: `Comment` argument is not yet added to the `model.Field` method
https://github.com/cwqt/refract/blob/983fbfbe098d84c245cbb6f91de71ecb9999be56/src/public/model.ts#L14-L17

**Comment by cwqt** [comment]
> Comment argument is not yet added to the model.Field method

Ah sorry, misread your OP & implemented Comment as a modifier rather than being a new argument

```typescript
m.Field("id", Int(Comment("This is a comment"));
```

I could change it to be more like:

```typescript
m.Field("id", Int(), "This is a comment");
````

if you prefer?

**Comment by cwqt** [comment]
Liked this a lot more than the `Comment()` modifier, has been implemented in https://github.com/cwqt/refract/commit/58b7b061e146cf8c061f7b1c7885867be550a0ae & released https://www.npmjs.com/package/@cwqt/refract/v/1.3.0
