### ISSUE TITLE
[Request] Relationships in more type safe and shorter way

### ISSUE THREAD

**Issue by ragokan** [cwqt/refract#9]
Currently we do define relationships like this:
```ts
User.Field("email", p.String(p.Unique, db.VarChar(255)))
  .Field("Role", Role("USER"))
  .Relation("posts", p.OneToMany(Post));

Post.Field("title", p.String(db.VarChar(255)))
  .Field("published", p.Boolean(p.Default(false)))
  .Relation("author", p.ManyToOne(User, p.Fields("authorId"), p.References("id")))
  .Field("authorId", p.Int());
  ```
  
  But can we do something like this to not add another field and have relation in the *ManyToOne* area?
  
  ```ts
  Post.Field("title", p.String(db.VarChar(255)))
  .Field("published", p.Boolean(p.Default(false)))
  .Relation("author", p.ManyToOne(User, p.Fields("authorId", p.Int()), p.References("id")))
  ```
  
  *p refers to `import * as p from "@cwqt/refract";`*

**Comment by cwqt** [comment]
Cool little idea, added in https://github.com/cwqt/refract/commit/97f208e35fbef52752841180bda79ad68784f1c0 & released with [1.3.2](https://www.npmjs.com/package/@cwqt/refract/v/1.3.2)
